version: '3'
services:
  backend:
    image: ooqitech/tethys:latest
    volumes:
      - ./server/tethys/settings.py:/usr/local/src/tethys/tethys/settings.py
    hostname: backend
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 80:80
